# Generated by Django 2.2.13 on 2020-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200616_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='give_info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='want_info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1'),
        ),
    ]
