# Generated by Django 2.2.13 on 2020-06-16 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200616_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Give_info',
        ),
        migrations.RemoveField(
            model_name='give',
            name='author',
        ),
        migrations.RemoveField(
            model_name='give',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='give',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='give',
            name='text',
        ),
        migrations.RemoveField(
            model_name='give',
            name='title',
        ),
        migrations.AddField(
            model_name='give',
            name='delite_flug',
            field=models.BooleanField(default=False, verbose_name='論理削除フラグ'),
        ),
        migrations.AddField(
            model_name='give',
            name='delivery_infomation',
            field=models.TextField(max_length=200, null=True, verbose_name='引き渡し情報'),
        ),
        migrations.AddField(
            model_name='give',
            name='final_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='give',
            name='give_id',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='give',
            name='give_name',
            field=models.CharField(default=1, max_length=30, verbose_name='GIVEアイテム名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='give',
            name='give_reason',
            field=models.TextField(max_length=200, null=True, verbose_name='あげたい理由'),
        ),
        migrations.AddField(
            model_name='give',
            name='item_id',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='give',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公開日時'),
        ),
        migrations.AddField(
            model_name='give',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='give',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
    ]
