# Generated by Django 2.2.13 on 2020-06-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200616_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mail_address',
            field=models.EmailField(max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mail_address',
            field=models.EmailField(max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(max_length=200, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail_address',
            field=models.EmailField(max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='want_info',
            name='mail_address',
            field=models.EmailField(max_length=254, null=True, verbose_name='メールアドレス'),
        ),
    ]
