# Generated by Django 2.2.13 on 2020-06-16 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200617_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give_comment',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='give_comment',
            name='give_comment',
        ),
        migrations.RemoveField(
            model_name='give_comment',
            name='give_comment_id',
        ),
        migrations.RemoveField(
            model_name='give_comment',
            name='give_id',
        ),
        migrations.RemoveField(
            model_name='give_comment',
            name='register_date',
        ),
        migrations.AddField(
            model_name='give_comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='give_comment',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='give_comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='give_comment',
            name='give',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='give_comments', to='blog.Give'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='give_comment',
            name='text',
            field=models.TextField(default=1, verbose_name='GIVEコメント'),
            preserve_default=False,
        ),
    ]
