# Generated by Django 2.2.13 on 2020-06-16 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200617_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give_comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='give_comment',
            name='text',
            field=models.TextField(null=True, verbose_name='GIVEコメント'),
        ),
    ]
