# Generated by Django 2.2.13 on 2020-06-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_give_give_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='give_user',
        ),
    ]
