# Generated by Django 2.2.13 on 2020-06-18 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_remove_give_give_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='PROFILEコメント')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('delite_flug', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Want_info',
        ),
        migrations.RemoveField(
            model_name='give',
            name='delite_flug',
        ),
        migrations.RemoveField(
            model_name='give',
            name='give_id',
        ),
        migrations.RemoveField(
            model_name='give',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='give',
            name='open_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='want',
            name='author',
        ),
        migrations.RemoveField(
            model_name='want',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='want',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='want',
            name='text',
        ),
        migrations.RemoveField(
            model_name='want',
            name='title',
        ),
        migrations.RemoveField(
            model_name='want_comment',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='want_comment',
            name='register_date',
        ),
        migrations.RemoveField(
            model_name='want_comment',
            name='want_comment',
        ),
        migrations.RemoveField(
            model_name='want_comment',
            name='want_comment_id',
        ),
        migrations.RemoveField(
            model_name='want_comment',
            name='want_id',
        ),
        migrations.AddField(
            model_name='give',
            name='give_information',
            field=models.TextField(max_length=200, null=True, verbose_name='商品詳細情報'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='want',
            name='delivery_infomation',
            field=models.CharField(max_length=30, null=True, verbose_name='引き渡し方法'),
        ),
        migrations.AddField(
            model_name='want',
            name='final_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='want',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='イメージ写真'),
        ),
        migrations.AddField(
            model_name='want',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='want',
            name='want_information',
            field=models.TextField(max_length=200, null=True, verbose_name='商品詳細情報'),
        ),
        migrations.AddField(
            model_name='want',
            name='want_name',
            field=models.CharField(default=1, max_length=30, verbose_name='WANTアイテム名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='want',
            name='want_reason',
            field=models.TextField(max_length=200, null=True, verbose_name='ほしい理由'),
        ),
        migrations.AddField(
            model_name='want_comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='want_comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='want_comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='want_comment',
            name='text',
            field=models.TextField(null=True, verbose_name='WANTコメント'),
        ),
        migrations.AddField(
            model_name='want_comment',
            name='want',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='want_comments', to='blog.Want'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='give',
            name='delivery_infomation',
            field=models.CharField(max_length=30, null=True, verbose_name='引き渡し方法'),
        ),
        migrations.AlterField(
            model_name='give',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='イメージ写真'),
        ),
        migrations.AddField(
            model_name='profile_comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='blog.Profile'),
        ),
    ]
