# Generated by Django 2.2.13 on 2020-06-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200617_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='item_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
