# Generated by Django 2.2.13 on 2020-06-18 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20200617_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='item_image',
        ),
        migrations.AddField(
            model_name='give',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='want',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='want',
            name='emergency_attribute',
            field=models.CharField(choices=[('1', 'お急ぎ欲しいです！'), ('2', '欲しいです！')], default=1, max_length=30, verbose_name='お急ぎ度'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='PROFILEコメント')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('delite_flug', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='blog.Profile')),
            ],
        ),
    ]
