# Generated by Django 2.2.13 on 2020-06-18 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20200618_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='want',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='want',
            name='emergency_attribute',
            field=models.CharField(choices=[('1', '高！'), ('2', '中'), ('3', '低')], default=1, max_length=30, verbose_name='お急ぎ度'),
            preserve_default=False,
        ),
    ]
