# Generated by Django 2.2.13 on 2020-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200618_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='give',
            name='final_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='give',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
