# Generated by Django 2.2.13 on 2020-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200618_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give_comment',
            name='delite_flug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mail_address',
        ),
        migrations.RemoveField(
            model_name='profile_comment',
            name='delite_flug',
        ),
        migrations.RemoveField(
            model_name='want',
            name='delivery_infomation',
        ),
        migrations.RemoveField(
            model_name='want_comment',
            name='delite_flug',
        ),
        migrations.AlterField(
            model_name='give',
            name='give_name',
            field=models.CharField(max_length=50, verbose_name='GIVEアイテム名称'),
        ),
        migrations.AlterField(
            model_name='give_comment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(max_length=200, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='profile_comment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='want',
            name='emergency_attribute',
            field=models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=30, verbose_name='お急ぎ度'),
        ),
        migrations.AlterField(
            model_name='want',
            name='final_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='want',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='want',
            name='want_name',
            field=models.CharField(max_length=50, verbose_name='WANTアイテム名称'),
        ),
    ]
