# Generated by Django 2.2.13 on 2020-06-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200618_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='delivery_infomation',
            field=models.CharField(max_length=30, null=True, verbose_name='引き渡し方法（※必須）'),
        ),
        migrations.AlterField(
            model_name='give',
            name='give_information',
            field=models.TextField(max_length=200, null=True, verbose_name='詳細情報（※必須）'),
        ),
        migrations.AlterField(
            model_name='give',
            name='give_name',
            field=models.CharField(max_length=50, verbose_name='タイトル（※必須）'),
        ),
        migrations.AlterField(
            model_name='give',
            name='give_reason',
            field=models.TextField(max_length=200, null=True, verbose_name='あげたい理由（※任意）'),
        ),
        migrations.AlterField(
            model_name='give',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='イメージ写真（※任意）'),
        ),
        migrations.AlterField(
            model_name='give_comment',
            name='text',
            field=models.TextField(null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(max_length=200, null=True, verbose_name='ひとこと（※任意）'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30, verbose_name='社員名（※必須）'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像（※任意）'),
        ),
        migrations.AlterField(
            model_name='profile_comment',
            name='text',
            field=models.TextField(null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='want',
            name='emergency_attribute',
            field=models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=30, verbose_name='緊急度（※選択）'),
        ),
        migrations.AlterField(
            model_name='want',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='イメージ写真（※任意）'),
        ),
        migrations.AlterField(
            model_name='want',
            name='want_information',
            field=models.TextField(max_length=200, null=True, verbose_name='詳細情報（※必須）'),
        ),
        migrations.AlterField(
            model_name='want',
            name='want_name',
            field=models.CharField(max_length=50, verbose_name='タイトル（※必須）'),
        ),
        migrations.AlterField(
            model_name='want',
            name='want_reason',
            field=models.TextField(max_length=200, null=True, verbose_name='ほしい理由（※任意）'),
        ),
        migrations.AlterField(
            model_name='want_comment',
            name='text',
            field=models.TextField(null=True, verbose_name='コメント'),
        ),
    ]
