# Generated by Django 2.2.13 on 2020-06-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200622_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give_comment',
            name='give',
        ),
    ]
