# Generated by Django 2.2.13 on 2020-06-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_give_comment_give'),
    ]

    operations = [
        migrations.AddField(
            model_name='give_comment',
            name='give',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='give_comments', to='blog.Give'),
            preserve_default=False,
        ),
    ]
